package project.springservice.project_wp.model;

public enum ProductEnum {
    Haircut,
    BeardTrim,
    HairExtension,
    HairColor,
    MensHaircut,
    HairImplants,
    AfricanBraiding,
    BeardShaping,
    BeardShave,
    BeardGrooming,
    BeardColoring,
    StraightRazorShape,
    MustacheTrim,

    HairDye,
    Manicure,
    Pedicure,
    AcrylicNails,
    NailArt,
    NailRepair,
    GelPedicure,
    GelNails,
    NailExtension,
    GelTips,
    FrenchManicure,
    FrenchPedicure,
    MedicalPedicure,
    ManicureForMen,
    PedicureForMen,
    KidsPedicure,

    Facials,
    DermaPlanning,
    Peel,
    ChemicalPeel,
    Dermabrassion,
    Facelift,
    FacialTreatments,
    MesoTherapy,
    FacialRejuvenation,
    FacePeel,
    NonSurgicalFaceLift,

    LashLift,
    EyelashExtensions,
    VolumeLashes,
    Microblading,
    EyebrowWaxing,
    EyebrowShaping,
    LashTing,
    EyebrowTinting,
    FakeEyelashes,
    EyebrowThreading,
    EyeleashPerm,
    EyebrowExtensions,
    PermanentEyebrows,
    LashLamination,

    AyuvedicMassage,
    HeadMassage,
    SwedishMassage,
    TwentyFourHourMassage,
    DeepTisueMassage,
    HotStoneMassage,
    Cupping,
    SportsMassage,
    TherapeuticMassage,
    LymphaticMassage,
    FootMassage,
    CouplesMassage,
    FullBodyMassage,
    BodyMassage,
    BackMassage,
    RelaxMassage,
    PregnancyMassage,
    ThaiMassage,
    HawaiianMassage,
    AsianMassage,

    NaturalMakeup,
    AirbrushMakeup,
    NewYearsMakeup,
    BodyPainting,

    Sauna,
    BodyScrub,
    BodyConturing,
    SprayTan,
    CouplesSpa,
    SugarScrub,
    FacialSpa,
    MensSpa,
    Tanning,
    BridalGroups,
    MeditationRoom,

    Tattoo,
    TemporaryTattoos,
    TattooParlors,
    EyebrowTattoo,
    WatercolorTattoo,

    WeightLoss,
    BodyComposition,
    NutritionConsultant,

    NosePiercing,
    BodyPiercing,
    BabyEarPiercing,
    EarPiercings,
    BellyButtonPiercing,
    TongueRings,

    Weave,
    Waxing,
}
